// Generated by CoffeeScript 1.3.3
(function() {
  var appendInfo, el;

  el = document.getElementById("info");

  appendInfo = function(string) {
    return el.innerHTML += string;
  };

  appendInfo('So the index.html defined the compilations? Neat!');

}).call(this);
